//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QConsoleWeb.DAL.EF.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dictionaries
    {
        public int id { get; set; }
        public string schema_name { get; set; }
        public string table_name { get; set; }
    }
}
