//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QConsoleWeb.DAL.EF.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logtable
    {
        public int gid { get; set; }
        public string action { get; set; }
        public string username { get; set; }
        public string address { get; set; }
        public System.DateTime timechange { get; set; }
        public string tablename { get; set; }
        public string context { get; set; }
        public Nullable<int> gidnum { get; set; }
        public string query { get; set; }
        public string tableschema { get; set; }
    }
}
